### ISSUE TITLE
WARNING::Unwanted advisory type: CEBA.  Skipping

### ISSUE THREAD

**Issue by kerub77** [vmfarms/generate_updateinfo#16]
Hi,
on a Red Hat 7.3 the script gives me these kind of warnings:
example:
WARNING:root:Unwanted advisory type: CEBA_2016__0946.  Skipping
WARNING:root:Unwanted advisory type: CEBA_2015__1394.  Skipping
WARNING:root:Unwanted advisory type: CEBA_2014__0437.  Skipping
WARNING:root:Unwanted advisory type: CEBA_2015__1396.  Skipping
WARNING:root:Unwanted advisory type: CEBA_2015__1397.  Skipping
WARNING:root:Unwanted advisory type: CEBA_2015__0409.  Skipping
WARNING:root:Unwanted advisory type: CEBA_2015__1392.  Skipping
WARNING:root:Unwanted advisory type: CEBA_2015__1393.  Skipping

Is it ok or should I use your script on a CentOS?

**Comment by stevemeier** [comment]
It doesn't matter what platform you run the script on.

Which parameters have you used? Did you specify -t or --type?

**Comment by kerub77** [comment]
./generate_updateinfo.py -s all -t security -r 7 <(bzip2 -dc /tmp/errata.latest.xml.bz2)

the same on a Centos7 doesn't give me any warnings but the final result seems the same.

**Comment by Dan0maN** [comment]
CEBA is for CentOS.  Red Hat's should have been a RHBA.

**Comment by stevemeier** [comment]
@kerub77 Then that's correct. CEBA is a bugfix while you specified to consider security (CESA) only with -t security

**Comment by kerub77** [comment]
Yes I need only security, so it's should be fine for my scope?
